# Generated by Django 4.2 on 2026-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('reps', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.FloatField(default=100.0, help_text='Percentage accuracy based on form')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
