# Generated by Django 4.2 on 2026-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_seed',
            field=models.CharField(default='Gym', max_length=50),
        ),
    ]
